#############################################################################
###                      Validazione documenti CDA                        ###
#############################################################################


#############################################################################
# 1) Validazione Documento LAB
# EXPECTED: 200 OK
#############################################################################
# @name validation
POST {{$dotenv BASE_URL}}:8010/v1/documents/validation
FSE-JWT-Signature: {{$dotenv JWT_LAB}}
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="requestBody";
Content-Type: application/json

{
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "activity": "VERIFICA"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file/LAB.pdf" 
Content-Type: application/octet-stream

< ./files/pdf/LAB.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


#############################################################################
# 2) Validazione Documento LDO
# EXPECTED: 200 OK
#############################################################################
# @name validation
POST {{$dotenv BASE_URL}}:8010/v1/documents/validation
FSE-JWT-Signature: {{$dotenv JWT_LDO}}
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="requestBody";
Content-Type: application/json

{
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "activity": "VERIFICA"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file/LDO.pdf" 
Content-Type: application/octet-stream

< ./files/pdf/LDO.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


#############################################################################
# 3) Validazione Documento PSS
# EXPECTED: 200 OK
#############################################################################
# @name validation
POST {{$dotenv BASE_URL}}:8010/v1/documents/validation
FSE-JWT-Signature: {{$dotenv JWT_PSS}}
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="requestBody";
Content-Type: application/json

{
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "activity": "VERIFICA"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file/PSS.pdf" 
Content-Type: application/octet-stream

< ./files/pdf/PSS.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


#############################################################################
# 4) Validazione Documento RAD
# EXPECTED: 200 OK
#############################################################################
# @name validation
POST {{$dotenv BASE_URL}}:8010/v1/documents/validation
FSE-JWT-Signature: {{$dotenv JWT_RAD}}
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="requestBody";
Content-Type: application/json

{
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "activity": "VERIFICA"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file/RAD.pdf"
Content-Type: application/octet-stream

< ./files/pdf/RAD.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


#############################################################################
# 5) Validazione Documento RSA
# EXPECTED: 200 OK
#############################################################################
# @name validation
POST {{$dotenv BASE_URL}}:8010/v1/documents/validation
FSE-JWT-Signature: {{$dotenv JWT_RSA}}
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="requestBody";
Content-Type: application/json

{
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "activity": "VERIFICA"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file/RSA.pdf" 
Content-Type: application/octet-stream

< ./files/pdf/RSA.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


#############################################################################
# 6) Validazione Documento SING_VACC
# EXPECTED: 200 OK
#############################################################################
# @name validation
POST {{$dotenv BASE_URL}}:8010/v1/documents/validation
FSE-JWT-Signature: {{$dotenv JWT_SING_VACC}}
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="requestBody";
Content-Type: application/json

{
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "activity": "VERIFICA"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file/SING_VACC.pdf" 
Content-Type: application/octet-stream

< ./files/pdf/SING_VACC.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


#############################################################################
# 7) Validazione Documento CERT_VACC
# EXPECTED: 200 OK
#############################################################################
# @name validation
POST {{$dotenv BASE_URL}}:8010/v1/documents/validation
FSE-JWT-Signature: {{$dotenv JWT_CERT_VACC}}
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="requestBody";
Content-Type: application/json

{
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "activity": "VERIFICA"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file/CERT_VACC.pdf" 
Content-Type: application/octet-stream

< ./files/pdf/CERT_VACC.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


#############################################################################
# 8) Validazione Documento VPS
# EXPECTED: 200 OK
#############################################################################
# @name validation
POST {{$dotenv BASE_URL}}:8010/v1/documents/validation
FSE-JWT-Signature: {{$dotenv JWT_VPS}}
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="requestBody";
Content-Type: application/json

{
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "activity": "VERIFICA"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file/VPS.pdf" 
Content-Type: application/octet-stream

< ./files/pdf/VPS.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


#############################################################################
# 9) Analisi dei Log emessi durante la validazione
# EXPECTED: 17 Log emessi
#############################################################################
@from = 1970-01-01
@to = 2100-01-01
####
GET {{$dotenv BASE_URL}}:9097/v1/search-events-log?startDate={{from}}&endDate={{to}}