@identificativoDoc=2.16.840.1.113883.2.9.2.110.4.4^12345

#############################################################################
# Validazione Documento RAD
#############################################################################
# @name validation
POST {{$dotenv IT_FSE_GTW_DISPATCHER}}/v1/documents/validation
FSE-JWT-Signature: FAKE_HEADER.{{$dotenv JWT_RAD_PAYLOAD}}.FAKE_SIGNATURE
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="requestBody";
Content-Type: application/json

{
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "activity": "VALIDATION"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file/RAD.pdf" 
Content-Type: application/octet-stream

< ./../files/pdf/RAD.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


#############################################################################
# Pubblicazione Documento RAD
#############################################################################
# @name creation
POST {{$dotenv IT_FSE_GTW_DISPATCHER}}/v1/documents 
FSE-JWT-Signature: FAKE_HEADER.{{$dotenv JWT_RAD_WITH_HASH_PAYLOAD}}.FAKE_SIGNATURE
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="requestBody";
Content-Type: application/json

{
  "tipologiaStruttura": "Ospedale",
  "attiCliniciRegoleAccesso": [ "PUBLICPOL" ],
  "tipoDocumentoLivAlto": "WOR",
  "assettoOrganizzativo": "AD_PSC001",
  "conservazioneANorma": "string",
  "tipoAttivitaClinica": "PHR",
  "identificativoSottomissione": "string",
  "healthDataFormat": "CDA", 
  "mode": "ATTACHMENT", 
  "identificativoDoc": "{{identificativoDoc}}",
  "identificativoRep": "ID_REPOSITORY",
  "priorita": true
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file/RAD.pdf" 
Content-Type: application/octet-stream

< ./../files/pdf/RAD.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


#############################################################################
# Verifica Stato Transazione
#############################################################################
GET {{$dotenv IT_FSE_GTW_DISPATCHER}}/v1/status/{{creation.response.body.workflowInstanceId}}


#############################################################################
# Analisi dei Log emessi durante il flusso di creazione
#############################################################################
@from = 1970-01-01
@to = 2100-01-01
####
GET {{$dotenv IT_FSE_SRV_LOG_INGESTION}}/v1/search-events-log?startDate={{from}}&endDate={{to}}